import Navbar from "@components/Navbar"
import "@styles/global.css"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="transition-all ease-in">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
