

import Navbar from "@components/Navbar"
import AppSessionProvider from "@components/Context/AppSessionProvider"
import AppContext from "@components/Context/AppContext";
import "@styles/global.css"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="transition-all ease-in" suppressHydrationWarning>

        <AppContext>
          <AppSessionProvider>
            <Navbar />
            {children}
          </AppSessionProvider>
        </AppContext>
      </body>
    </html>
  )
}
